# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oc_populator.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 691, 521))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(79, 56, 251, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_host = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_host.setObjectName("label_host")
        self.verticalLayout_2.addWidget(self.label_host)
        self.label_admin_user = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_admin_user.setObjectName("label_admin_user")
        self.verticalLayout_2.addWidget(self.label_admin_user)
        self.label_admin_pw = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_admin_pw.setObjectName("label_admin_pw")
        self.verticalLayout_2.addWidget(self.label_admin_pw)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_host = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.verticalLayout.addWidget(self.lineEdit_host)
        self.lineEdit_admin_user = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_admin_user.setObjectName("lineEdit_admin_user")
        self.verticalLayout.addWidget(self.lineEdit_admin_user)
        self.lineEdit_admin_pw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_admin_pw.setObjectName("lineEdit_admin_pw")
        self.verticalLayout.addWidget(self.lineEdit_admin_pw)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.pushButton_store_credentials = QtWidgets.QPushButton(self.tab)
        self.pushButton_store_credentials.setGeometry(QtCore.QRect(50, 220, 171, 51))
        self.pushButton_store_credentials.setObjectName("pushButton_store_credentials")
        self.pushButton_check_connection = QtWidgets.QPushButton(self.tab)
        self.pushButton_check_connection.setGeometry(QtCore.QRect(220, 220, 171, 51))
        self.pushButton_check_connection.setToolTipDuration(9)
        self.pushButton_check_connection.setObjectName("pushButton_check_connection")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_users = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_users.setGeometry(QtCore.QRect(30, 20, 241, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_users.sizePolicy().hasHeightForWidth())
        self.tableWidget_users.setSizePolicy(sizePolicy)
        self.tableWidget_users.setRowCount(10)
        self.tableWidget_users.setColumnCount(2)
        self.tableWidget_users.setObjectName("tableWidget_users")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(1, item)
        self.pushButton_new_element = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_new_element.setGeometry(QtCore.QRect(80, 430, 113, 32))
        self.pushButton_new_element.setObjectName("pushButton_new_element")
        self.pushButton_create_users = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_create_users.setGeometry(QtCore.QRect(280, 60, 171, 31))
        self.pushButton_create_users.setObjectName("pushButton_create_users")
        self.pushButton_store_users = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_store_users.setGeometry(QtCore.QRect(280, 20, 171, 31))
        self.pushButton_store_users.setObjectName("pushButton_store_users")
        self.pushButton_delete_users = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_delete_users.setGeometry(QtCore.QRect(280, 100, 171, 31))
        self.pushButton_delete_users.setObjectName("pushButton_delete_users")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_files = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_files.setGeometry(QtCore.QRect(90, 70, 401, 161))
        self.tableWidget_files.setRowCount(4)
        self.tableWidget_files.setObjectName("tableWidget_files")
        self.tableWidget_files.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_files.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_files.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_files.setHorizontalHeaderItem(2, item)
        self.tableWidget_files.horizontalHeader().setDefaultSectionSize(123)
        self.pushButton_upload_files = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_upload_files.setGeometry(QtCore.QRect(510, 100, 121, 31))
        self.pushButton_upload_files.setObjectName("pushButton_upload_files")
        self.pushButton_store_files = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_store_files.setGeometry(QtCore.QRect(510, 70, 121, 31))
        self.pushButton_store_files.setObjectName("pushButton_store_files")
        self.pushButton_add_row_files = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_add_row_files.setGeometry(QtCore.QRect(210, 240, 161, 31))
        self.pushButton_add_row_files.setObjectName("pushButton_add_row_files")
        self.tableWidget_folders = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_folders.setGeometry(QtCore.QRect(90, 280, 281, 161))
        self.tableWidget_folders.setRowCount(4)
        self.tableWidget_folders.setObjectName("tableWidget_folders")
        self.tableWidget_folders.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_folders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_folders.setHorizontalHeaderItem(1, item)
        self.tableWidget_folders.horizontalHeader().setDefaultSectionSize(123)
        self.pushButton_add_row_folders = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_add_row_folders.setGeometry(QtCore.QRect(210, 450, 161, 31))
        self.pushButton_add_row_folders.setObjectName("pushButton_add_row_folders")
        self.pushButton_store_folders = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_store_folders.setGeometry(QtCore.QRect(380, 280, 121, 31))
        self.pushButton_store_folders.setObjectName("pushButton_store_folders")
        self.pushButton_create_folders = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_create_folders.setGeometry(QtCore.QRect(380, 310, 121, 31))
        self.pushButton_create_folders.setObjectName("pushButton_create_folders")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_shares = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_shares.setGeometry(QtCore.QRect(30, 20, 441, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_shares.sizePolicy().hasHeightForWidth())
        self.tableWidget_shares.setSizePolicy(sizePolicy)
        self.tableWidget_shares.setShowGrid(True)
        self.tableWidget_shares.setRowCount(10)
        self.tableWidget_shares.setColumnCount(4)
        self.tableWidget_shares.setObjectName("tableWidget_shares")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shares.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shares.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shares.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shares.setHorizontalHeaderItem(3, item)
        self.pushButton_create_shares = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_create_shares.setGeometry(QtCore.QRect(480, 350, 171, 81))
        self.pushButton_create_shares.setObjectName("pushButton_create_shares")
        self.pushButton_new_row_shares = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_new_row_shares.setGeometry(QtCore.QRect(180, 430, 113, 32))
        self.pushButton_new_row_shares.setObjectName("pushButton_new_row_shares")
        self.tabWidget.addTab(self.tab_3, "")
        self.textBrowser_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_info.setGeometry(QtCore.QRect(730, 50, 256, 481))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 8, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 8, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser_info.setPalette(palette)
        self.textBrowser_info.setObjectName("textBrowser_info")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(730, 20, 251, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_info.setFont(font)
        self.label_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info.setAutoFillBackground(False)
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.textBrowser_info.raise_()
        self.label_info.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ownCloud Populator"))
        self.label_host.setText(_translate("MainWindow", "Host"))
        self.label_admin_user.setText(_translate("MainWindow", "Admin User"))
        self.label_admin_pw.setText(_translate("MainWindow", "Admin Password"))
        self.pushButton_store_credentials.setText(_translate("MainWindow", "Store Credentials"))
        self.pushButton_check_connection.setText(_translate("MainWindow", "Check connection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Connection"))
        item = self.tableWidget_users.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_users.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Password"))
        self.pushButton_new_element.setText(_translate("MainWindow", "Add row"))
        self.pushButton_create_users.setText(_translate("MainWindow", "Create users"))
        self.pushButton_store_users.setText(_translate("MainWindow", "Store users"))
        self.pushButton_delete_users.setText(_translate("MainWindow", "Delete users"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Create users"))
        item = self.tableWidget_files.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_files.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File Path Origin"))
        item = self.tableWidget_files.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "File Path Destination"))
        self.pushButton_upload_files.setText(_translate("MainWindow", "Upload files"))
        self.pushButton_store_files.setText(_translate("MainWindow", "Store uploads"))
        self.pushButton_add_row_files.setText(_translate("MainWindow", "Add row"))
        item = self.tableWidget_folders.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_folders.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New folder"))
        self.pushButton_add_row_folders.setText(_translate("MainWindow", "Add row"))
        self.pushButton_store_folders.setText(_translate("MainWindow", "Store folders"))
        self.pushButton_create_folders.setText(_translate("MainWindow", "Create folders"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Files and Folders"))
        item = self.tableWidget_shares.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sharer"))
        item = self.tableWidget_shares.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sharee"))
        item = self.tableWidget_shares.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Path"))
        item = self.tableWidget_shares.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type"))
        self.pushButton_create_shares.setText(_translate("MainWindow", "Create shares"))
        self.pushButton_new_row_shares.setText(_translate("MainWindow", "Add row"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Create shares"))
        self.label_info.setText(_translate("MainWindow", "Information"))

