# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oc_populator.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 771, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(79, 56, 251, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_host = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_host.setObjectName("label_host")
        self.verticalLayout_2.addWidget(self.label_host)
        self.label_admin_user = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_admin_user.setObjectName("label_admin_user")
        self.verticalLayout_2.addWidget(self.label_admin_user)
        self.label_admin_pw = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_admin_pw.setObjectName("label_admin_pw")
        self.verticalLayout_2.addWidget(self.label_admin_pw)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_host = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.verticalLayout.addWidget(self.lineEdit_host)
        self.lineEdit_admin_user = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_admin_user.setObjectName("lineEdit_admin_user")
        self.verticalLayout.addWidget(self.lineEdit_admin_user)
        self.lineEdit_admin_pw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_admin_pw.setObjectName("lineEdit_admin_pw")
        self.verticalLayout.addWidget(self.lineEdit_admin_pw)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.pushButton_store_credentials = QtWidgets.QPushButton(self.tab)
        self.pushButton_store_credentials.setGeometry(QtCore.QRect(50, 220, 171, 51))
        self.pushButton_store_credentials.setObjectName("pushButton_store_credentials")
        self.pushButton_check_connection = QtWidgets.QPushButton(self.tab)
        self.pushButton_check_connection.setGeometry(QtCore.QRect(220, 220, 171, 51))
        self.pushButton_check_connection.setToolTipDuration(9)
        self.pushButton_check_connection.setObjectName("pushButton_check_connection")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_users = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_users.setGeometry(QtCore.QRect(30, 20, 241, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_users.sizePolicy().hasHeightForWidth())
        self.tableWidget_users.setSizePolicy(sizePolicy)
        self.tableWidget_users.setRowCount(10)
        self.tableWidget_users.setColumnCount(2)
        self.tableWidget_users.setObjectName("tableWidget_users")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(1, item)
        self.pushButton_new_element = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_new_element.setGeometry(QtCore.QRect(80, 430, 113, 32))
        self.pushButton_new_element.setObjectName("pushButton_new_element")
        self.pushButton_create_users = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_create_users.setGeometry(QtCore.QRect(290, 340, 171, 81))
        self.pushButton_create_users.setObjectName("pushButton_create_users")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_host.setText(_translate("MainWindow", "Host"))
        self.label_admin_user.setText(_translate("MainWindow", "Admin User"))
        self.label_admin_pw.setText(_translate("MainWindow", "Admin Password"))
        self.pushButton_store_credentials.setText(_translate("MainWindow", "Store Credentials"))
        self.pushButton_check_connection.setText(_translate("MainWindow", "Check connection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        item = self.tableWidget_users.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_users.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Password"))
        self.pushButton_new_element.setText(_translate("MainWindow", "Add row"))
        self.pushButton_create_users.setText(_translate("MainWindow", "Create users"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

